apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  mongod.conf: |
    # MongoDB configuration file
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
      port: 27017
    replication:
      replSetName: rs0