apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: standard
  hostPath:
    path: /home/aman/Documents/Db_Users
    type: DirectoryOrCreate
